public class Main {
    public static void main(String[] args) {
        System.out.println("Hello, Apriliyan Bintek!");
        System.out.println("NIM : 2604004");
        System.out.println("Jurusan : Teknologi Informasi");
        System.out.println("Alasan memilih Teknologi Informasi : Karena saya ingin menjadi seorang programmer yang handal dan dapat membuat aplikasi yang bermanfaat bagi banyak orang.");
    }
}   